Add code about spawning world and robot
AuTURBO/StrideSim pull request #10
Opened 2024-01-02 21:45 UTC by mqjinwon

https://github.com/AuTURBO/StrideSim/assets/42585679/0311efe1-8a72-461c-b0d0-4f726c6a0764

- pegasus code 중 필요한 틀 가져와서 적용
  - 작동시키기 위해 많은 부분을 삭제하였으므로, 추후 비교하며 보완해야 함

2024-01-06 06:02 UTC, harderthan requested changes
코멘트 한번에 submit 한다고 리뷰가 늦었습니다.  
페가수스 코드와 모두 비교해보진 못했어요. 엉터리 코멘트가 있더라도 이해부탁드려요.

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +"""
이 라인들은 삭제되어야 할 것 같습니다.  
Description은 필요하다고 생각되시면 남겨도 괜찮을 것 같구요.

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +rot_ENU_to_NED = Rotation.from_quat(q_ENU_to_NED)
사족보행 로봇의 경우 ENU 좌표계만 써도 모든 구현이 가능하지 않나요? NED 좌표계가 필요할까요?   
필요하지 않다면 삭제하는 것은 어떨까요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +rot_FLU_to_FRD = Rotation.from_quat(q_FLU_to_FRD)
이것도 마찬가지 입니다.   
당장 필요하지 않다면 삭제해두는 것이 좋을 것 같아요.

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/extension.py
> +
이 라인을 지워주실래요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/extension.py
> +# Python garbage collenction and asyncronous API
여기 코드의 대부분이 `ui` 디렉토리 하위로 옮겨져야 한다고 하셨죠?  
이 파일 최상단에 이것에 대한 코멘트와 TODO를 남겨주실 수 있을까요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +# Importing Lock in ordef to have a multithread safe Pegasus singleton that manages the entire Pegasus extension
nitpick.     

```suggestion
# Importing lock in order to have a multithread safe Pegasus singleton that manages the entire Pegasus extension.
```

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        StrideInterface._is_initialized = True
이 두 라인은 `__init__` 함수 내에서 가장 마지막에 호출되는 것이 더 바람직한 것 같아요.  
옮기는게 어떨까요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        #asyncio.ensure_future(self._world.initialize_simulation_context_async())
이 코드는 페가수스 코드에도 남아있는 쓰지 않는 코드네요.  
삭제해주실래요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +class QuadrupedRobotConfig:
여기 개행 2줄이 들어가야 포매팅이 맞지 않나요?   
이상하게도 pylint에서는 안잡히는군요...

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +            config=QuadrupedRobotConfig(),
`QuadrupedRobotConfig` 에 `stage_prefix`와 `usd_file`가 포함되어 있으니까, argument로 congig만 넣어줘도 되지 않나요?  
괜찮다면 58 line에서도 config 값으로 입력해주면 되겠네요.

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/state.py
> +"""
여기도 이 코멘트들을 지워주실래요?   
다른 파일들도 동일하게 적용할 수 있을까요?

2024-01-06 06:02 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/vehicle.py
> +    def sim_start_stop(self, event):
`sim_start_stop` 보다 `sim_start`와 `sim_stop` 함수로 나누는게 좋을 것 같아요.  
아직 이 함수를 쓰는 곳은 없지만, start해야 될 상황과 stop해야 할 상황이 명확할 것 같아요.

2024-01-07 10:51 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +class QuadrupedRobotConfig:
넵 개행이 들어가는 것이 맞는 것 같습니다.

2024-01-07 11:03 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +            config=QuadrupedRobotConfig(),
이건 isaacsim (robot)에서 제공해주는 class를 상속받다보니 어쩔수 없이 포함해야하는 인자로 보입니다.
번거롭더라도 중복해서 사용해줘야할 것 같습니다.

2024-01-07 11:04 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +"""
삭제했습니다.

2024-01-07 11:05 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +rot_ENU_to_NED = Rotation.from_quat(q_ENU_to_NED)
이건 state.py에 사용되고 있어서, 차근차근 지워나가도록 하겠습니다.

2024-01-07 11:06 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/common/coordinate_system.py
> +rot_FLU_to_FRD = Rotation.from_quat(q_FLU_to_FRD)
이것도 state.py에 사용되고 있어서, 차근차근 지워나가도록 하겠습니다.

2024-01-07 11:09 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/extension.py
> +# Python garbage collenction and asyncronous API
추가했습니다.

2024-01-07 11:10 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/extension.py
> +
삭제했습니다.

2024-01-07 11:11 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/vehicles/state.py
> +"""
삭제했습니다.

2024-01-07 11:13 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        #asyncio.ensure_future(self._world.initialize_simulation_context_async())
혹시 어떤 부분이 쓰지 않는 코드인가요? 
initialize_world 함수는 world를 부를 때 사용하고 있습니다.

2024-01-07 11:24 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/vehicles/vehicle.py
> +    def sim_start_stop(self, event):
나누었습니다.

2024-01-07 11:27 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        StrideInterface._is_initialized = True
수정했습니다.

2024-01-08 02:11 UTC, harderthan commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        #asyncio.ensure_future(self._world.initialize_simulation_context_async())
```
#asyncio.ensure_future(self._world.initialize_simulation_context_async())
```
108 번째 주석처리된 라인을 말씀드렸었어요!

2024-01-08 02:14 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +class QuadrupedRobotConfig:
그럼 개행을 넣어주실 수 있을까요?

2024-01-08 02:17 UTC, harderthan commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +            config=QuadrupedRobotConfig(),
그럼, 반대로 RobotConfig에 `stage_prefix`와 `usd_file`을 삭제하는 건 어떤가요?  
같은 값을 중복해서 들고 있을 필요가 없어 보여요.

2024-01-14 10:58 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/vehicles/quadrupedrobot/quadrupedrobot.py
> +class QuadrupedRobotConfig:
아 수정했었는데 다시 빠졌군요. 추가했습니다.

2024-01-14 11:00 UTC, mqjinwon commented on exts/stride.simulator/stride/simulator/interfaces/stride_sim_interface.py
> +        #asyncio.ensure_future(self._world.initialize_simulation_context_async())
삭제했습니다!

2024-01-14 12:37 UTC, harderthan approved these changes

2024-01-14 12:38 UTC, merged