Test pylint
AuTURBO/StrideSim pull request #8
Opened 2023-12-29 08:44 UTC by mqjinwon

Add the pylint.sh file to simplify testing.

2024-01-02 13:06 UTC, harderthan requested changes

2024-01-02 13:06 UTC, harderthan commented on test_pylint.sh
> +#! /bin/bash
마치 pylint 자체를 테스트하는 것 같아 보여서요.   
파일명을 `pylint.sh` 또는 `run_pylint.sh`라고 지으면 어떨까요?

2024-01-02 15:42 UTC, mqjinwon commented on test_pylint.sh
> +#! /bin/bash
run_pylint.sh으로 이름 변경하겠습니다.

2024-01-03 10:27 UTC, harderthan approved these changes

2024-01-03 11:48 UTC, merged